version: '3'

services:
  web:
    image: nginx
    build:
      context: .
      dockerfile: infra/docker/nginx/Dockerfile
    ports:
        - "8080:80"
    volumes:
        - ./infra/docker/nginx/conf.d:/etc/nginx/conf.d
    links:
        - php
  php:
    image: php:7-fpm
    build:
      context: .
      dockerfile: infra/docker/fpm/Dockerfile
    volumes:
    - ./design-patterns:/var/www/html